name: CI

on:
  push:
  pull_request:

jobs:
  quality:
    name: Lint and Test
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        go: ['1.25']
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.ref }}
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}
      - name: Install tools
        run: make tools
      - name: Lint
        run: make lint
      - name: Test
        run: make test
